In [2]:
import numpy as np

### 5.1

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


In [3]:
e = np.identity(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
a = e*5
a

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [6]:
p = np.linalg.inv(a)
print(p)

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


### 5.2

Вычислите определитель:

In [8]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
round(np.linalg.det(a))

60.0

### 5.3 1)

Вычислите матрицу, обратную данной:

In [9]:
p = np.linalg.inv(a)
p

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### 5.3 2)

Приведите пример матрицы 4х4, ранг которой равен 1.

In [10]:
a = np.array([[4, 4, 4, 4], [0, 0, 0, 0], [0, 0, 0, 0],[0, 0, 0, 0]])
a

array([[4, 4, 4, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 5.4

Вычислите скалярное произведение двух векторов:  

In [13]:
a = np.array([1, 5])
b = np.array([2, 8])
s = np.inner(a,b)
s

42

### 5.5

Вычислите смешанное произведение трех векторов:

In [17]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
v = np.cross(a, b)
np.inner(v,c)

228.5

In [18]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
w = np.cross(b, c)
np.inner(w,a)

228.5