In [15]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import scipy 
import scipy.linalg  

### 5.1

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


In [3]:
e = np.identity(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
a = e*5
a

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [6]:
p = np.linalg.inv(a)
print(p)

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


### 5.2

Вычислите определитель:

In [8]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
round(np.linalg.det(a))

60.0

### 5.3 1)

Вычислите матрицу, обратную данной:

In [9]:
p = np.linalg.inv(a)
p

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### 5.3 2)

Приведите пример матрицы 4х4, ранг которой равен 1.

In [10]:
a = np.array([[4, 4, 4, 4], [0, 0, 0, 0], [0, 0, 0, 0],[0, 0, 0, 0]])
a

array([[4, 4, 4, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 5.4

Вычислите скалярное произведение двух векторов:  

In [13]:
a = np.array([1, 5])
b = np.array([2, 8])
s = np.inner(a,b)
s

42

### 5.5

Вычислите смешанное произведение трех векторов:

In [17]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
v = np.cross(a, b)
np.inner(v,c)

228.5

In [18]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
w = np.cross(b, c)
np.inner(w,a)

228.5

### 6.1

Решите линейную систему:

In [3]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

### 6.2

Найдите псевдорешение:

In [13]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,-5,0],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

### 6.3

Сколько решений имеет линейная система:

Начальная система имеет 0 решений

In [10]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A,B)

array([ 2.83726777e+16, -5.67453553e+16,  2.83726777e+16])

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([1,2,3])
np.linalg.solve(A,B)

array([-0.23333333,  0.46666667,  0.1       ])

### 6.4

Вычислите LU-разложение матрицы:

In [16]:
A = np.array([ [1,2,3], [2,16,21], [4,28,73] ])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [17]:
B = np.array([4, 1, 7])
np.linalg.solve(A, B)

array([ 5.12962963, -0.67592593,  0.07407407])

### 6.5

Найдите нормальное псевдорешение недоопределенной системы:

In [20]:
def Q(x, y):
    return (x**2 + y**2 + z**2)

In [21]:
A = np.array([[1, 2,-1],[8,-5,2]])
B = np.array([1,12])
np.linalg.lstsq(A, B)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))